"""Small online-learning policy used by representative World agents.

The policy separates *what an agent can do* from *when it does it*.  Actions
remain bounded, auditable economic primitives, while selection is learned from
the utility change observed on the next tick.  This avoids brittle scripted
scenario chains without putting an LLM in the deterministic hot path.
"""
from __future__ import annotations

import math
import random
from dataclasses import dataclass, field
from typing import Mapping

__all__ = ["ActionOption", "AdaptivePolicy", "PolicyDecision"]


@dataclass(frozen=True, slots=True)
class ActionOption:
    """An available action and its contextual linear prior."""

    name: str
    weights: Mapping[str, float] = field(default_factory=dict)
    bias: float = 0.0


@dataclass(frozen=True, slots=True)
class PolicyDecision:
    action: str
    confidence: float
    scores: Mapping[str, float]
    exploratory: bool


@dataclass(slots=True)
class _Memory:
    q: dict[str, float]
    previous_action: str | None = None
    previous_utility: float | None = None
    visits: dict[str, int] = field(default_factory=dict)


class AdaptivePolicy:
    """Contextual bandit with one-step temporal-difference updates.

    A separate memory is kept per actor/country.  Context weights provide safe
    economic priors; Q-values then adapt those priors to outcomes generated by
    the simulation.  Seeded randomness keeps runs reproducible.
    """

    def __init__(
        self,
        options: tuple[ActionOption, ...],
        *,
        learning_rate: float = 0.16,
        exploration: float = 0.08,
        temperature: float = 0.35,
        seed: int = 0,
    ) -> None:
        if not options:
            raise ValueError("adaptive policy requires at least one action")
        self._options = options
        self._alpha = max(0.0, min(1.0, learning_rate))
        self._epsilon = max(0.0, min(1.0, exploration))
        self._temperature = max(0.05, temperature)
        self._rng = random.Random(seed)
        self._memory: dict[str, _Memory] = {}

    def decide(
        self,
        key: str,
        *,
        features: Mapping[str, float],
        utility: float,
    ) -> PolicyDecision:
        memory = self._memory.setdefault(
            key,
            _Memory(q={option.name: 0.0 for option in self._options}),
        )
        self._learn(memory, utility)

        scores = {
            option.name: (
                option.bias
                + sum(option.weights.get(name, 0.0) * float(value)
                      for name, value in features.items())
                + memory.q[option.name]
                + self._novelty_bonus(memory, option.name)
            )
            for option in self._options
        }

        exploratory = self._rng.random() < self._epsilon
        if exploratory:
            chosen = self._rng.choice(self._options).name
        else:
            chosen = self._sample_softmax(scores)

        probabilities = self._softmax(scores)
        memory.previous_action = chosen
        memory.previous_utility = float(utility)
        memory.visits[chosen] = memory.visits.get(chosen, 0) + 1
        return PolicyDecision(
            action=chosen,
            confidence=probabilities[chosen],
            scores=scores,
            exploratory=exploratory,
        )

    def q_values(self, key: str) -> dict[str, float]:
        memory = self._memory.get(key)
        return dict(memory.q) if memory else {}

    def _learn(self, memory: _Memory, utility: float) -> None:
        action = memory.previous_action
        previous = memory.previous_utility
        if action is None or previous is None:
            return
        reward = max(-1.0, min(1.0, float(utility) - previous))
        memory.q[action] += self._alpha * (reward - memory.q[action])
        memory.q[action] = max(-1.5, min(1.5, memory.q[action]))

    def _novelty_bonus(self, memory: _Memory, action: str) -> float:
        total = sum(memory.visits.values()) + 1
        visits = memory.visits.get(action, 0)
        return 0.06 * math.sqrt(math.log(total + 1) / (visits + 1))

    def _sample_softmax(self, scores: Mapping[str, float]) -> str:
        probabilities = self._softmax(scores)
        needle = self._rng.random()
        cumulative = 0.0
        for option in self._options:
            cumulative += probabilities[option.name]
            if needle <= cumulative:
                return option.name
        return self._options[-1].name

    def _softmax(self, scores: Mapping[str, float]) -> dict[str, float]:
        peak = max(scores.values())
        exp_scores = {
            name: math.exp((score - peak) / self._temperature)
            for name, score in scores.items()
        }
        total = sum(exp_scores.values())
        return {name: value / total for name, value in exp_scores.items()}
