ARG sourceimage=econith/econith-quant
ARG sourcetag=develop
FROM ${sourceimage}:${sourcetag}

# Install dependencies
COPY requirements-freqai.txt requirements-freqai-rl.txt /econith/

RUN pip install -r requirements-freqai.txt -r requirements-freqai-rl.txt --user --no-cache-dir
