ARG sourceimage=econith/econith-quant
ARG sourcetag=develop
FROM ${sourceimage}:${sourcetag}

# Install dependencies
COPY requirements-freqai.txt /econith/

RUN pip install -r requirements-freqai.txt --user --no-cache-dir
